### ISSUE TITLE
Rails 3 Support

### ISSUE THREAD

**Issue by bensie** [devinterface/authlogic_subdomain_fu_startup_app#1]
Currently does not work with Rails 3 because of the way relation objects are created instead of AR objects.

**Comment by xponrails** [comment]
Hi Bensie.

I've just created a branch for Rails 3 (beta 2) support. See http://github.com/devinterface/authlogic_subdomain_fu_startup_app/tree/rails3

It is still under development (I was just able to create an account and it's main user), due to some problems related to subdomains support in routes.rb

I don't know how much time I can spend on it this week, but patches are appreciated.

Stefano
